name: Test
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'windows-2019', 'macos-12' ]
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run tests
        run: poetry run pytest --cov=sigmaiq --cov-report term --cov-report xml:cov.xml -vv
      - name: Store coverage for badge
        if: ${{ runner.os == 'Linux' }}
        run: poetry run python print-coverage.py >> $GITHUB_ENV
      - name: Create coverage badge
        if: ${{ github.repository == 'AttackIQ/SigmAIQ' && github.event_name == 'push' && runner.os == 'Linux' }}
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: f6d72f7ec2b300546a114fd80d371f7e
          filename: slincoln-aiq-SigmAIQ.json
          label: Coverage
          message: ${{ env.COVERAGE }}
          color: ${{ env.COVERAGE_COLOR }}
